apiVersion: apps/v1
kind: Deployment
metadata:
  name: iemdb-mysql
  labels:
    app: iemdb-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iemdb-mysql
  template:
    metadata:
      labels:
        app: iemdb-mysql
    spec:
      volumes:
        - name: database-pv-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim
      containers:
        - name: iemdb-mysql
          image: m.docker-registry.ir/mysql:latest
          ports:
            - containerPort: 3306
          resources:
            limits:
              memory: "500Mi"
              cpu: 0.3
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: database-pv-storage
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "Linuxpass1234$"
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mysql-db
                  key: database